made base.html.twig, including header and footer
WildCodeSchool/tours-php-2009-project3-amon pull request #1
Opened 2020-12-09 18:11 UTC by KevinRoig

2020-12-10 08:26 UTC, rickifox approved these changes

2020-12-11 09:17 UTC, RomainClair requested changes
You should use the semantic web tags to give meaning to your web pages
You should probably not commit empy files

2020-12-11 09:17 UTC, RomainClair commented on templates/base.html.twig
> +        <div class="navbar">
div class navbar should probably be a nav

2020-12-11 09:17 UTC, RomainClair commented on templates/base.html.twig
> +            </div>
And because this is a navigation menu : i.e. a list of links
It should be an html list of links not a div of divs

2020-12-11 10:03 UTC, KevinRoig commented
Changes will be made on "gallery" branch, i close this branch.

2020-12-11 10:03 UTC, closed without merging