Form
WildCodeSchool/tours-php-2009-project3-amon pull request #12
Opened 2021-01-06 14:08 UTC by KevinRoig

2021-01-06 14:12 UTC, AurelieFqt submitted a review, later dismissed

2021-01-06 14:54 UTC, AurelieFqt submitted a review, later dismissed

2021-01-06 15:27 UTC, RomainClair requested changes
The upload directory should probably be in the gitignore and all the test images must not be in the git repository

2021-01-06 16:13 UTC, AurelieFqt approved these changes

2021-01-07 08:20 UTC, RomainClair approved these changes

2021-01-07 08:20 UTC, merged