Edit form
WildCodeSchool/tours-php-2009-project3-amon pull request #14
Opened 2021-01-07 15:24 UTC by AurelieFqt

2021-01-07 15:37 UTC, KevinRoig approved these changes
ok

2021-01-08 09:49 UTC, RomainClair requested changes
You probably shouldn't delete migrations already in the master or dev branch
Your Image entity should probably have constraints for the symfony validator to do it's job.
For example, you should check that the category is on of the possible choices

2021-01-08 09:49 UTC, RomainClair commented on src/Controller/GalleryController.php
> +     * @Route("/gallerie-design-metallique/{categorie}/{id}",
The categorie parameter seems unnecessary

2021-01-08 09:49 UTC, RomainClair commented on src/Controller/GalleryController.php
> +            $this->getDoctrine()->getManager()->flush();
It is a symfony best practice to use dependency injection for services (like the EntityManager)

2021-01-08 09:49 UTC, RomainClair commented on src/Controller/GalleryController.php
> +            'image' => $image,
The image twig parameter seems unnecessary

2021-01-08 09:49 UTC, RomainClair commented on src/Controller/GalleryController.php
> +            $entityManager->flush();
Once again : It is a symfony best practice to use dependency injection for services (like the EntityManager)

2021-01-11 07:57 UTC, closed without merging