create passage secret gallery with delete function
WildCodeSchool/tours-php-2009-project3-amon pull request #23
Opened 2021-01-19 11:53 UTC by AurelieFqt

2021-01-19 12:07 UTC, rickifox commented on templates/passage/index.html.twig
> +                duis. Velit ea consequat ut sint nostrud elit sunt.</p>
Oui c'est vrai que c'est un peu redondant vous avez bien fait de supprimer la fin

2021-01-19 12:10 UTC, rickifox submitted a review, later dismissed

2021-01-19 15:36 UTC, rickifox submitted a review, later dismissed

2021-01-20 08:22 UTC, RomainClair requested changes

2021-01-20 08:22 UTC, RomainClair commented on templates/gallery/design.html.twig
> +>>>>>>> a8238930a0dee2fb4d735acf0d5c1f64fb52a99f
Unresolved conflict

2021-01-20 08:31 UTC, AurelieFqt commented on templates/gallery/design.html.twig
> +>>>>>>> a8238930a0dee2fb4d735acf0d5c1f64fb52a99f
its ok

2021-01-20 08:40 UTC, rickifox approved these changes

2021-01-20 09:15 UTC, RomainClair approved these changes

2021-01-20 09:15 UTC, merged